### ISSUE TITLE
bug：mtr rocksdb.add_index_inplace fail

### ISSUE THREAD

**Issue by lixingyun-git** [topling/mytopling#2]
mtr test “rocksdb.add_index_inplace 'write_committed'” failed

output：
CURRENT_TEST: rocksdb.add_index_inplace
mysqltest: At line 411: Query 'ALTER TABLE t1 DROP INDEX idx, ADD UNIQUE KEY idx (j)' succeeded, should have failed with error '1062'

**Comment by rockeet** [comment]
Fixed by commit: 34f2622c5eeb17a7264fefe25a454e27b94a20d0
